# general settings for image SR training
name: 005_MambaIRv2_Denoise_finetune_from_pretrain
model_type: MambaIRv2Model
scale: 1
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: TrainSet
    type: PairedImageDataset
    dataroot_gt: /path/to/data/ntire2026/01denoise/mix_data02_dfol4k8k/imgH
    dataroot_lq: /path/to/data/ntire2026/01denoise/mix_data02_dfol4k8k/imgL
#    meta_info_file: hat/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: DIV2K_VAL
    type: PairedImageDataset
#    dataroot_gt: ./datasets/Set5/GTmod4
    dataroot_gt: /path/to/Xformer/datasets/DIV2K/denoising_val_gt
    dataroot_lq: /path/to/Xformer/datasets/DIV2K/denoising_val_input
    io_backend:
      type: disk


# network structures
network_g:
  type: MambaIRv2
  upscale: 4
  in_chans: 3
#  img_size: 64
  img_size: 128
  img_range: 1.
  embed_dim: 174
  d_state: 16
  depths: [6, 6, 6, 6, 6, 6, 6, 6, 6]
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6]
  window_size: 16
  inner_rank: 64
  num_tokens: 128
  convffn_kernel_size: 5
  mlp_ratio: 2.0
#  upsampler: 'pixelshuffle'
#  resi_connection: '1conv'


# path
path:
  # for classic SRx4, we use the x2 Model to initialize and halve the training iteration and lr for fast training
  pretrain_network_g: experiments/005_MambaIRv2_Denoise_finetune_from_pretrain_archived_20260308_233650/models/net_g_50000.pth
  strict_load_g: false
  resume_state: ~


# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
#    lr: !!float 1e-4
#    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    # milestones: [ 250000, 400000, 450000, 475000 ]
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  # total_iter: 500000
  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
#    type: L1Loss
    type: MSELoss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
#  val_freq: !!float 5e3
#  save_img: true
#  val_freq: !!float 5e6
  val_freq: !!float 5e6
  save_img: false

#  metrics:
#    psnr: # metric name, can be arbitrary
#      type: calculate_psnr
#      crop_border: 4
#      test_y_channel: true



# logging settings
logger:
  print_freq: 200
#  save_checkpoint_freq: !!float 5e3
#  save_checkpoint_freq: !!float 5e4
  save_checkpoint_freq: !!float 25000
  #  use_tb_logger: true
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500