name: 004_My_train_MambaIRv2_DIV2K_level50_hx
model_type: MambaIRv2Model
scale: 1
#num_gpu: 8
num_gpu: 1
#manual_seed: 10
manual_seed: 2025

# dataset and data loader settings
datasets:
  train:
    task: SR
#    noise: 50 # 15/25/50
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/denoising_train/gt_crops.lmdb
    dataroot_lq: datasets/DIV2K/denoising_train/input_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 128
#    gt_size: 160
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
#    num_worker_per_gpu: 32
    num_worker_per_gpu: 8
#    batch_size_per_gpu: 2
#    batch_size_per_gpu: 1
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: SR
#    noise: 50 # 15/25/50
    name: div2k-val
    type: PairedImageDataset
#    dataroot_gt: ./datasets/GoPro/test/target.lmdb
#    dataroot_lq: ./datasets/GoPro/test/input.lmdb
#    io_backend:
#      type: lmdb
    dataroot_gt: datasets/DIV2K/denoising_val_gt
    dataroot_lq: datasets/DIV2K/denoising_val_input
    io_backend:
      type: disk

# network structures
network_g:
  type: MambaIRv2
  upscale: 1
  in_chans: 3
  img_size: 128
#  img_size: 160
  img_range: 1.
#  embed_dim: 174
  embed_dim: 48
  #  d_state: 16
  d_state: 8
  #  depths: [6, 6, 6,6,6,6]
#  num_heads: [6,6,6,6,6,6]
#  depths: [5, 5, 5, 5]
#  num_heads: [4, 4, 4, 4]
  depths: [6, 6, 6, 6]
  num_heads: [6, 6, 6, 6]
  window_size: 16
#  inner_rank: 64
#  num_tokens: 128
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 5
#  mlp_ratio: 2.
  mlp_ratio: 1.


path:
#  pretrain_network_g: ./experiments/pretrained_models/ColorDN_MambaIRv2_level15.pth
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    # lr: !!float 2e-4 # for noise 15
    lr: !!float 1e-4 # for noise 25/50
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000 ]
    # milestones: [ 800000, 1200000, 1400000, 1500000 ] # for noise 15
    # milestones: [ 400000, 600000, 700000, 750000 ] # for noise 25/50
    gamma: 0.5

  total_iter: 500000
  # total_iter: 1600000 # for noise 15
  # total_iter: 800000 # for noise 25/50
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
    eps: !!float 1e-3

# validation settings
val:
  val_freq: !!float 1e4
#  val_freq: !!float 5e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
#      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 0
#      test_y_channel: true
      test_y_channel: false

# logging settings
logger:
#  print_freq: 200
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
#  save_checkpoint_freq: !!float 5e4
  #  use_tb_logger: true
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
